server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #durid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/egou?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456